### ISSUE TITLE
Some abbreviations need an explanation

### ISSUE THREAD

**Issue by guntbert** [digitalocean/tos#2]
Please keep in mind that not all customers have American English as their first language.

Case in point:

You are talking about _SLA Credits_ but never explain what _SLA_ is, how one gets such a credit.

**Comment by andrewsomething** [comment]
Hi! That's a really good point. SLA stands for service-level agreement. We commit to a 99.99% uptime SLA. If we fail to live up to that we will grant a credit for the lost time. We'll get that worked into the next update.

**Comment by guntbert** [comment]
Thank you, much clearer now :smiley_cat:
